### ISSUE TITLE
Problem with refuse in authorize dialog

### ISSUE THREAD

**Issue by jamesxv7** [SciDevs/delicious-api#34]
In the authorization process when the API request access to the data, the **Refuse** option does nothing. A response should be trigger in order to properly implement the rejection in a third party application. Right now any callback logic never will know if the authorization was rejected.

**Comment by peoplemerge** [comment]
Good to know.  Can you provide a couple of sample CURL requests that illustrate the issue?  That could help us isolate and fix it.

**Comment by jamesxv7** [comment]
Sure! But the problem are not related to the CURL requests. Once I authenticate I can do any CURL request without issues. The problem occurs in the Authorize URL. I'm using: **https://delicious.com/auth/authorize** and for the access Token Url, **https://avosapi.delicious.com/api/v1/oauth/token**. 

When Im redirected to the authorize link on Delicious once I click **Refuse** the request do nothing. There is no response. 

![delicious-refuse-disable](https://cloud.githubusercontent.com/assets/121668/6139917/cfc0fb24-b167-11e4-8e92-98b42cf8a017.png)

**Comment by jamesxv7** [comment]
After analyzing the situation I realize the following warning in Chrome Console: _“Scripts may close only the windows that were opened by it.”_

This links explains in more detail the warning: http://stackoverflow.com/a/19768082/1014839

If I call the API from the same window the option **Refuse** simply will not work. But if a made the call from a new pop-up window it will work.

**Comment by peoplemerge** [comment]
Yes.  I noticed all oauth connections open new windows, that explains it!  Thanks for the explanation.
